### ISSUE TITLE
Panic while parsing js

### ISSUE THREAD

**Issue by p4fg** [rusty-ecma/RESSA#81]
Doing some research and stumbled across a js-file which makes the parser panic and crash.
This does not look like a memory/stack-issue.

# Stacktrace

```
thread 'main' panicked at 'byte index 961599 is not a char boundary; it is inside '\u{a0}' (bytes 961598..961600) of `/*! jQuery v3.5.1 | (c) JS Foundation and other contributors | jquery.org/license */
!function(e,t){"use strict";"object"==typeof module&&"object"==typeof module.exports?module.exports=e.document?t(e,!0):function(e){if(!e.document)throw new Error("jQuery r`[...]', /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/ress-0.11.4/src/manual_scanner.rs:283:32
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:65:14
   2: core::str::slice_error_fail_rt
   3: core::str::slice_error_fail
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/str/mod.rs:86:9
   4: core::str::traits::<impl core::slice::index::SliceIndex<str> for core::ops::range::Range<usize>>::index
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/str/traits.rs:218:21
   5: core::str::traits::<impl core::ops::index::Index<I> for str>::index
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/str/traits.rs:65:9
   6: ress::manual_scanner::ManualScanner::next_regex
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/ress-0.11.4/src/manual_scanner.rs:283:32
   7: ress::Scanner::get_next_token
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/ress-0.11.4/src/lib.rs:267:13
   8: <ress::Scanner as core::iter::traits::iterator::Iterator>::next
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/ress-0.11.4/src/lib.rs:205:9
   9: ressa::spanned::Parser<CH>::next_item
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/ressa-0.8.0/src/spanned/mod.rs:6237:39
  10: ressa::spanned::Parser<CH>::expect_punct
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/ressa-0.8.0/src/spanned/mod.rs:6305:20
  11: ressa::spanned::Parser<CH>::parse_args
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/ressa-0.8.0/src/spanned/mod.rs:6072:26
  12: ressa::spanned::Parser<CH>::parse_left_hand_side_expr_allow_call
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/ressa-0.8.0/src/spanned/mod.rs:5922:21
  13: ressa::spanned::Parser<CH>::parse_update_expr
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/ressa-0.8.0/src/spanned/mod.rs:5730:24
  14: ressa::spanned::Parser<CH>::parse_unary_expression
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/ressa-0.8.0/src/spanned/mod.rs:5606:13
  15: ressa::spanned::Parser<CH>::parse_exponentiation_expression
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/ressa-0.8.0/src/spanned/mod.rs:5544:20
  16: ressa::spanned::Parser<CH>::parse_binary_expression
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/ressa-0.8.0/src/spanned/mod.rs:5444:27
  17: ressa::spanned::Parser<CH>::parse_conditional_expr
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/ressa-0.8.0/src/spanned/mod.rs:5413:20
  18: ressa::spanned::Parser<CH>::parse_assignment_expr
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/ressa-0.8.0/src/spanned/mod.rs:4753:31
  19: ressa::spanned::Parser<CH>::parse_assignment_after_start
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/ressa-0.8.0/src/spanned/mod.rs:4915:21
  20: ressa::spanned::Parser<CH>::parse_assignment_expr
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/ressa-0.8.0/src/spanned/mod.rs:4860:30
  21: ressa::spanned::Parser<CH>::parse_expression
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/ressa-0.8.0/src/spanned/mod.rs:2282:19
  22: ressa::spanned::Parser<CH>::parse_labelled_statement
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/ressa-0.8.0/src/spanned/mod.rs:2151:20
  23: ressa::spanned::Parser<CH>::parse_statement
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/ressa-0.8.0/src/spanned/mod.rs:1019:21
  24: ressa::spanned::Parser<CH>::parse_statement_list_item
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/ressa-0.8.0/src/spanned/mod.rs:523:28
  25: ressa::spanned::Parser<CH>::parse_block
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/ressa-0.8.0/src/spanned/mod.rs:2315:24
  26: ressa::spanned::Parser<CH>::parse_statement
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/ressa-0.8.0/src/spanned/mod.rs:988:29
  27: ressa::spanned::Parser<CH>::parse_if_clause
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/ressa-0.8.0/src/spanned/mod.rs:1575:9
  28: ressa::spanned::Parser<CH>::parse_if_stmt
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/ressa-0.8.0/src/spanned/mod.rs:1534:26
  29: ressa::spanned::Parser<CH>::parse_statement
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/ressa-0.8.0/src/spanned/mod.rs:1070:44
  30: ressa::spanned::Parser<CH>::parse_statement_list_item
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/ressa-0.8.0/src/spanned/mod.rs:513:32
  31: ressa::spanned::Parser<CH>::parse_function_source_el
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/ressa-0.8.0/src/spanned/mod.rs:2743:23
  32: ressa::spanned::Parser<CH>::parse_func
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/ressa-0.8.0/src/spanned/mod.rs:2653:20
  33: ressa::spanned::Parser<CH>::parse_fn_stmt
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/ressa-0.8.0/src/spanned/mod.rs:1590:20
  34: ressa::spanned::Parser<CH>::parse_statement_list_item
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/ressa-0.8.0/src/spanned/mod.rs:481:32
  35: ressa::spanned::Parser<CH>::next_part
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/ressa-0.8.0/src/spanned/mod.rs:6849:25
  36: <ressa::spanned::Parser<CH> as core::iter::traits::iterator::Iterator>::next
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/ressa-0.8.0/src/spanned/mod.rs:6880:18
  37: <&mut I as core::iter::traits::iterator::Iterator>::next
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/iter/traits/iterator.rs:3878:9
  38: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/iter/traits/iterator.rs:2237:29
  39: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/iter/adapters/mod.rs:195:9
  40: core::iter::traits::iterator::Iterator::try_for_each
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/iter/traits/iterator.rs:2299:9
  41: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::next
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/iter/adapters/mod.rs:178:9
  42: alloc::vec::Vec<T,A>::extend_desugared
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/alloc/src/vec/mod.rs:2857:35
  43: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/alloc/src/vec/spec_extend.rs:18:9
  44: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/alloc/src/vec/spec_from_iter_nested.rs:43:9
  45: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/alloc/src/vec/spec_from_iter.rs:33:9
  46: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/alloc/src/vec/mod.rs:2757:9
  47: core::iter::traits::iterator::Iterator::collect
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/iter/traits/iterator.rs:1836:9
  48: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter::{{closure}}
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/result.rs:2075:49
  49: core::iter::adapters::try_process
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/iter/adapters/mod.rs:164:17
  50: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/result.rs:2075:9
  51: core::iter::traits::iterator::Iterator::collect
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/iter/traits/iterator.rs:1836:9
  52: ressa::spanned::Parser<CH>::parse
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/ressa-0.8.0/src/spanned/mod.rs:361:43
  53: ressa::Parser<CH>::parse
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/ressa-0.8.0/src/lib.rs:341:19
  54: parsebug::main
             at ./src/main.rs:9:25
  55: core::ops::function::FnOnce::call_once
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

# Code to reproduce the bug

This was tested with latest versions of RESS and RESSA.

```
use ressa::Parser;
use resast::Program;
use std::fs;


fn main() {
    let js = fs::read_to_string("some.js").unwrap();
    let mut parser = Parser::new(&js).expect("Failed to create parser");
    let maybe_program = parser.parse();
    match maybe_program {
        Ok(program) => {
            println!("parsed successfully");
            match program {
                Program::Script(_parts) => println!("found a script"),
                Program::Mod(_parts) => println!("found an es6 module"),
            }
        },
        Err(err) => {
            println!("parse error: {}", err);
        },
    }
    
}
```

File `some.js` attached as a zip-archive to this issue.
[some_js.zip](https://github.com/rusty-ecma/RESSA/files/10474381/some_js.zip)

My expectation would be that the parse() operation would return Err, not making everything crash.

**Comment by FreeMasen** [comment]
Thank you for the bug report, it seems that the regex detection is getting out of sync with the original source text. I am going to move this issue to the RESS project since that is where the bug is coming from and continue to investigate.
